In [1]:
import numpy as np

In [25]:
data = np.genfromtxt("./scenario1/horizon5/tr1.txt", delimiter=',', dtype=np.float64)

In [26]:
data.shape

(21, 23)

In [195]:
start = 0.48612
stop = 3.30463

In [202]:
# EUC cost (symm,3)
data = np.genfromtxt("./scenario3/horizon3/tr2.txt", delimiter=',', dtype=np.float64)
idx = np.where(np.logical_and(data[:, 0] >= start, data[:, 0] <= stop))[0]
np.sum(np.abs(data[idx, 0] - stop))

24.300450999999995

In [197]:
data[:, 0]

array([0.428424, 0.506235, 0.622693, 0.78106 , 1.02584 , 1.2107  ,
       1.34612 , 1.49756 , 1.69949 , 1.85002 , 2.0402  , 2.20855 ,
       2.37844 , 2.56532 , 2.80687 , 2.91391 , 3.01338 , 3.16726 ,
       3.30463 ])

In [198]:
# EUC cost (symm,5)
data = np.genfromtxt("./scenario3/horizon5/tr1.txt", delimiter=',', dtype=np.float64)
idx = np.where(np.logical_and(data[:, 0] >= start, data[:, 0] <= stop))[0]
np.sum(np.abs(data[idx, 0] - stop))

25.616861000000004

In [199]:
data[:, 0]

array([0.315502, 0.340147, 0.441109, 0.565678, 0.769211, 0.88864 ,
       1.10073 , 1.23718 , 1.41177 , 1.553   , 1.66401 , 1.72052 ,
       1.83455 , 1.92218 , 2.07078 , 2.19367 , 2.60812 , 2.79856 ,
       3.03575 , 3.19047 , 3.30166 , 3.43297 , 3.56252 , 3.61392 ,
       3.59541 , 3.57351 , 3.56714 , 3.56143 ])

In [200]:
# EUC cost (symm,7)
data = np.genfromtxt("./scenario3/horizon7/tr1.txt", delimiter=',', dtype=np.float64)
idx = np.where(np.logical_and(data[:, 0] >= start, data[:, 0] <= stop))[0]
np.sum(np.abs(data[idx, 0] - stop))

32.376816

In [201]:
data[:, 0]

array([0.48612 , 0.507727, 0.576818, 0.682574, 0.778846, 0.939159,
       1.10394 , 1.25504 , 1.42546 , 1.56053 , 1.71543 , 1.88973 ,
       2.06704 , 2.18254 , 2.36586 , 2.5096  , 2.72685 , 2.86755 ,
       2.98777 , 3.12081 , 3.27102 , 3.40619 , 3.54443 ])

In [4]:
# CoM error
np.mean(abs(data[:, 0]) - abs(data[:, 2]))

0.0035187391304347697

In [5]:
# Feet error
fl_error = data[:, 4] - data[:, 12]
fr_error = data[:, 6] - data[:, 14]
rl_error = data[:, 8] - data[:, 16]
rr_error = data[:, 10] - data[:, 18]

In [6]:
np.mean(fl_error)

-0.018617304347826092

In [7]:
np.mean(fr_error)

0.004045521739130405

In [8]:
np.mean(rl_error)

-0.014849869565217371

In [9]:
np.mean(rr_error)

-8.108695652174903e-05

In [10]:
np.mean([abs(np.mean(fl_error)), abs(np.mean(fr_error)), abs(np.mean(rl_error)), abs(np.mean(rr_error))])

0.009398445652173905

In [11]:
# Velocity error
vel_error = data[:, -2] - data[:, -1]

In [12]:
data[:, -1]

array([0.0207214, 0.164977 , 0.420722 , 0.47493  , 0.522705 , 0.616147 ,
       0.741966 , 0.529782 , 0.52834  , 0.580025 , 0.619332 , 0.654579 ,
       0.621989 , 0.479667 , 0.488559 , 0.391812 , 0.495109 , 0.521073 ,
       0.487526 , 0.5036   , 0.503576 , 0.52624  , 0.476339 ])

In [13]:
data[:, -2]

array([-0.00157671,  0.214114  ,  0.392109  ,  0.500593  ,  0.471431  ,
        0.518895  ,  0.562733  ,  0.512291  ,  0.476501  ,  0.549847  ,
        0.603095  ,  0.639818  ,  0.570157  ,  0.506274  ,  0.544863  ,
        0.729296  ,  0.529503  ,  0.468279  ,  0.472188  ,  0.47432   ,
        0.52936   ,  0.513181  ,  0.501233  ])

In [14]:
np.mean(vel_error)

-0.003965743913043481